twig_doc:
  components:
    - name: ButtonStandard
      title: My Button
      description: Lorem Ipsum
      tags:
        - Buttons
      parameters:
        color: String
        title: String
      variations:
        default:
          color: grey
          title: Default Button
        primary:
          color: blue
          title: Primary Button
